# Generated by Django 6.1 on 2026-08-12 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationCandidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateAffectation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffectationEvaluateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateAffectation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ADMISSION', 'Admission'), ('NON_ADMISSION', 'Non admission')], max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('dateDecision', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('dateEvaluation', models.DateTimeField(auto_now_add=True)),
                ('validee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationEtape',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('REUSSIE', 'Réussie'), ('ECHOUEE', 'Échouée'), ('ABSENT', 'Absent'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('dateEntree', models.DateTimeField(auto_now_add=True)),
                ('dateSortie', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('TECHNIQUE', 'Technique'), ('SOFT_SKILLS_MOTIVATION', 'Soft skills / Motivation')], max_length=30)),
                ('baremeMax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ordre', models.IntegerField()),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite', models.IntegerField()),
            ],
        ),
    ]
