# Generated by Django 6.1 on 2026-08-12 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagnes', '0002_initial'),
        ('candidatures', '0002_initial'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationevaluateur',
            name='evaluateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='candidature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_finale', to='candidatures.candidature'),
        ),
        migrations.AddField(
            model_name='etape',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='campagnes.cohorte'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationetape',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='candidatures.candidature'),
        ),
        migrations.AddField(
            model_name='participationetape',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='evaluations.etape'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.participationetape'),
        ),
        migrations.AddField(
            model_name='affectationcandidat',
            name='participation_etape',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_session', to='evaluations.participationetape'),
        ),
        migrations.AddField(
            model_name='question',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='campagnes.cohorte'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.question'),
        ),
        migrations.AddField(
            model_name='session',
            name='etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='evaluations.etape'),
        ),
        migrations.AddField(
            model_name='affectationevaluateur',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_evaluateurs', to='evaluations.session'),
        ),
        migrations.AddField(
            model_name='affectationcandidat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_candidats', to='evaluations.session'),
        ),
    ]
