# Generated by Django 6.0.6 on 2026-08-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_affectation_presence_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationevaluateur',
            name='roleEncadrement',
            field=models.CharField(choices=[('TECHNIQUE', 'Encadreur technique'), ('MOTIVATION', 'Encadreur motivation')], default='TECHNIQUE', max_length=20),
        ),
    ]
