# Generated by Django 6.0.6 on 2026-08-19 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_affectationevaluateur_roleencadrement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intitule', models.TextField()),
                ('explication', models.TextField(blank=True, help_text='Explication de la réponse affichée après évaluation', null=True)),
                ('typeQuestion', models.CharField(choices=[('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple')], default='CHOIX_UNIQUE', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('ordre', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionQCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('estCorrecte', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='evaluations.questionqcm')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TestQCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dureeMinutes', models.PositiveIntegerField(default=30, help_text='Durée maximale du test en minutes')),
                ('baremeTotal', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('notePassage', models.DecimalField(decimal_places=2, default=10.0, help_text="Note minimale pour valider l'étape", max_digits=5)),
                ('estPublie', models.BooleanField(default=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('creePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_crees', to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_qcm', to='evaluations.etape')),
            ],
            options={
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.AddField(
            model_name='questionqcm',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.testqcm'),
        ),
        migrations.CreateModel(
            name='PassageTestQCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateDebut', models.DateTimeField(auto_now_add=True)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('scoreObtenu', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOUMIS', 'Soumis'), ('EXPIRE', 'Expiré')], default='EN_COURS', max_length=20)),
                ('estAdmis', models.BooleanField(default=False)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passage_test_qcm', to='evaluations.participationetape')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='evaluations.testqcm')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseCandidatQCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('optionsChoisies', models.ManyToManyField(blank=True, to='evaluations.optionqcm')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.passagetestqcm')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_candidats', to='evaluations.questionqcm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('passage', 'question'), name='reponse_unique_par_question_passage')],
            },
        ),
    ]
