# Generated by Django 6.0.6 on 2026-08-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_questionqcm_optionqcm_testqcm_questionqcm_test_and_more'),
        ('evaluations', '0008_alter_decision_type'),
    ]

    operations = [
    ]
