# Generated by Django 6.1 on 2026-08-19 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampFormulaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TEXTE', 'Texte court'), ('EMAIL', 'Email'), ('TELEPHONE', 'Téléphone'), ('DATE', 'Date'), ('NOMBRE', 'Nombre'), ('LISTE_DEROULANTE', 'Liste déroulante'), ('CHOIX_MULTIPLES', 'Choix multiples'), ('CASE_A_COCHER', 'Case à cocher'), ('ZONE_TEXTE', 'Zone de texte'), ('FICHIER', 'Fichier')], max_length=30)),
                ('description', models.CharField(blank=True, help_text="Texte d'aide affiché sous le champ", max_length=512, null=True)),
                ('placeholderTexte', models.CharField(blank=True, max_length=255, null=True)),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('regleValidation', models.JSONField(blank=True, help_text='Règles de validation JSON : ex {"min": 2, "max": 100}', null=True)),
                ('typesMimeAutorises', models.CharField(blank=True, help_text='Ex: .pdf,.docx', max_length=255, null=True)),
                ('tailleMaxMo', models.IntegerField(blank=True, help_text='Taille max en Mo', null=True)),
            ],
            options={
                'verbose_name': 'Champ de formulaire',
                'verbose_name_plural': 'Champs de formulaire',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionChamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur', models.CharField(blank=True, help_text='Valeur technique (optionnel, égale au libellé par défaut)', max_length=255, null=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Option de champ',
                'verbose_name_plural': 'Options de champ',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('publie', models.BooleanField(default=False)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('campagne', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulaire', to='campagnes.campagne')),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['-dateCreation'],
            },
        ),
    ]
