# Generated by Django 6.1 on 2026-08-19 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0002_initial'),
        ('formulaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='creePar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulaires_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulaires', to='evaluations.etape'),
        ),
        migrations.AddField(
            model_name='champformulaire',
            name='formulaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='formulaires.formulaire'),
        ),
        migrations.AddField(
            model_name='optionchamp',
            name='champ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='formulaires.champformulaire'),
        ),
    ]
