# Generated by Django 6.1 on 2026-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du test')),
                ('campagne_assossiée', models.CharField(blank=True, max_length=255, null=True, verbose_name='Formation/Offre associée')),
                ('lien_ressource', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien de la ressource (URL)')),
                ('fichier_ressource', models.FileField(blank=True, null=True, upload_to='tests_resources/', verbose_name='Fichier de ressource')),
                ('description', models.TextField(verbose_name='Description / Consignes')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('nouveau', 'Nouveau')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
    ]
