# Generated by Django 6.1 on 2026-08-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_test', '0001_initial'),
        ('campagnes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='campagne_assossiee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='campagnes.campagne'),
        ),
    ]
