# Generated by Django 6.1 on 2026-08-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_candidat', models.CharField(max_length=100)),
                ('email_candidat', models.EmailField(max_length=254)),
                ('fichier_test', models.FileField(upload_to='soumissions/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
