# Generated by Django 6.1 on 2026-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_test', '0002_soumissiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_cloture',
            field=models.DateTimeField(default='2026-08-18 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='date_ouverture',
            field=models.DateTimeField(default='2026-08-30 12:00:00'),
            preserve_default=False,
        ),
    ]
