# Generated by Django 6.1 on 2026-08-12 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ACTIVATION', 'Activation'), ('CONVOCATION', 'Convocation'), ('RESULTAT', 'Résultat'), ('FIN_PARCOURS', 'Fin de parcours'), ('ADMISSION', 'Admission')], max_length=20)),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='candidatures.candidature')),
            ],
        ),
    ]
