# Generated by Django 6.1 on 2026-08-19 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagnes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='creePar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campagne',
            name='cohorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='campagnes.cohorte'),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to='campagnes.formation'),
        ),
    ]
