# Generated by Django 6.1 on 2026-08-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='duree',
        ),
    ]
