# Generated by Django 6.1 on 2026-08-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0003_remove_formation_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
