# Generated by Django 6.0.6 on 2026-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0004_alter_cohorte_nom_alter_formation_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cohorte',
            unique_together={('nom', 'formation')},
        ),
    ]
